/*********************************************************************************************
 *  Description : Name, description, version and build date of the loaded StreamLogger library
 *  License     : The unlicense (https://unlicense.org)
 *	Copyright	(C) 2024  Ignacio Pomar Ballestero
 ********************************************************************************************/

#pragma once
#ifndef _STREAM_LOGGER_LIBRARY_INFO_H_
#	define _STREAM_LOGGER_LIBRARY_INFO_H_

#	include "StreamLogger/StreamLoggerVersion.h"    // Generated by CMake in the build folder

namespace IgnacioPomar::Util::StreamLogger
{
	struct LibraryInfo
	{
			const char *name;
			const char *description;
			const char *version;      // "MAJOR.MINOR.PATCH"
			const char *buildDate;    // "YYYY-MM-DD HH:MM:SS", local time of the machine that built the library
			int versionMajor;
			int versionMinor;
			int versionPatch;
	};

	// The library that is loaded at run time (with a shared library it may differ from STREAMLOGGER_VERSION,
	// the version the program was compiled with)
	const LibraryInfo &getLibraryInfo () noexcept;

}    // namespace IgnacioPomar::Util::StreamLogger

#endif    // _STREAM_LOGGER_LIBRARY_INFO_H_
